name: Test

on:
  push:
    branches: [dev, main]
    paths: [src/**, tests/**]
  pull_request:
    paths: [src/**, tests/**]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    
    services:
      rabbitmq:
        image: rabbitmq:3.13.6
        ports: ["5672"]
          
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        env:
          AMQP_URI: amqp://localhost:${{ job.services.rabbitmq.ports[5672] }}
        run: uv run pytest
